Make gum more optional, list it in the README as a dependency

diff --git a/bin/jgit-cleanup-all-branches b/bin/jgit-cleanup-all-branches
--- a/bin/jgit-cleanup-all-branches
+++ b/bin/jgit-cleanup-all-branches
@@ -39,6 +39,11 @@ may_be_merged() {
     return 1
 }
 
+if ! hash gum ; then
+    error "Missing gum, please install it"
+    exit 99
+fi
+
 for branch in $(git branch); do
     if may_be_merged "${branch}" ; then
         git show -q "${branch}"
diff --git a/bin/jgit-new-branch b/bin/jgit-new-branch
--- a/bin/jgit-new-branch
+++ b/bin/jgit-new-branch
@@ -6,6 +6,11 @@ SCRIPT_DIR="$(dirname "$(readlink -f "${0}")")"
 
 common_setup_env
 
+if ! hash gum ; then
+    error "Missing gum, please install it"
+    exit 99
+fi
+
 cd "${REPO_DIR}" || {
     error "Unable to change directories"
     exit 255
